local hl = function(grp, opts)
	return vim.api.nvim_set_hl(0, grp, opts)
end

hl("NvimTreeGitNewIcon", { fg = "#389636" })
hl("NvimTreeGitFolderNewHL", { link = "NvimTreeGitNewIcon" })
hl("NvimTreeGitDirtyIcon", { fg = "#d1453b" })
hl("NormalFloat", { link = "Normal" })
hl("C_FloatBorder", { link = "Normal" })
hl("FloatBorder", { link = "Normal" })
hl("@variable", { fg = "#FCF75E" })
hl("@type.tsx", { fg = "#29AB87" })
hl("@punctuation.special", { fg = "#2D68C4" })
hl("@function", { fg = "#0000B8" })
hl("@function.call", { link = "@function.tsx" })
hl("@variable.member", { link = "@function.call.tsx" })
hl("@tag.delimiter.tsx", { link = "@tag.tsx" })
hl("@string", { fg = "#228B22" })
hl("@tag.attribute", { link = "@function.call.tsx" })
hl("@variable.level_1", { link = "@variable" })
hl("@variable.level_2", { fg = "#00B9E8" })
hl("@variable.level_3", { fg = "#EF9B0F" })
hl("@import.tsx", { fg = "#2295d4" })
hl("@tsx_tag_name.tsx", { link = "@import.tsx" })
hl("@tsx_tag_open_brace.tsx", { link = "@tsx_tag_name.tsx" })
hl("@tsx_tag_close_brace.tsx", { link = "@tsx_tag_name.tsx" })
hl("@tsx_attribute", { link = "@variable.level_3" })
